version: '3.8'

services:
  back:
    build: ./teste-back
    ports:
      - "8080:8080"
    networks:
      - app-network

  front:
    build: ./teste-front
    ports:
      - "80:80"
    networks:
      - app-network
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
