version: '3.8'

services:
  back:
    build: ./teste-back
    ports:
      - "8080:8080"
    networks:
      - app-network

  front:
    build: ./teste-front
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
