name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run containers
        run: |
          docker-compose -f docker-compose.yaml build
          docker-compose -f docker-compose.yaml up -d

      - name: Wait for services to be up
        run: |
          echo "Waiting for services to be up..."
          sleep 60

      - name: Validate localhost:80
        run: |
          status_code=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:80)
          echo "Status code: $status_code"
          if [ "$status_code" -ne 200 ]; then
            echo "Validation failed: Did not receive status 200"
            exit 1
          else
            echo "Validation successful: Received status 200"
          fi
